version: 2
formats: all
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - path: .
  